/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons2 {
  CustomIcons2._();

  static const _kFontFam = 'CustomIcons2';
  static const String? _kFontPkg = null;

  static const IconData record = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_call = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blood_sugar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_rate = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
